baseURL = "https://meik2333.com/"
languageCode = "zh-cn"
title = "MeiK's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "MeiK"
  description = "In solitude, where we are least alone."
  github = "MeiK2333"
  facebook = "MeiK2333"
  twitter = "MeiK2333"
  linkedin = "MeiK2333"
  instagram = "MeiK2333"
  tumblr = "MeiK2333"
  email = "meik2333@gmail.com"
  url = "https://meik2333.com"
  keywords = "blog, google analytics"
  rss = true
  stackoverflow="10389571"
  lastmod = true
  favicon = "/images/github.svg"
  location = "China"
  userStatusEmoji = "ğŸ˜€"
  enableLocalSearch = true # Set to true if you want to have keyword search locally(params.rss true is required)
  sponsorLink = "false" 
  customStyleFile = "your css file name"
  gtmId = "your gtm id"
  enableGitalk = false
  enableVssue = false
  enableAplyer = false
  enableDplyer = false
  enableCDN = false
  enableGithubFollowers = false
  enableGiscus = false

  [params.CDN]
    gitalk-css = ''
    gitalk-min-js = ''
    theme-mode-js = ''
    frameworks-min-css = ''
    github-min-css = ''
    github-style-css = '
    light-css = ''
    dark-css = ''
    syntax-css = ''
    toc-js = ''
    toc-css = ''
    #tip: you should enter full url 

   [params.gitalk]
     clientID = "Your client ID" # Your client ID
     clientSecret = "Your client secret" # Your client secret
     repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
     owner = "ventusoon" # æ‚¨çš„GitHub ID
     admin = "ventusoon" # æ‚¨çš„GitHub ID
     id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
     labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
     perPage = 15 # Pagination size, with maximum 100.
     pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
     createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
     distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
     proxy = "https://broken-wind-958e.29847163406422.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
     #more than gitalk
   [params.giscus]
     #install app first
     #https://github.com/apps/giscus
     #motified in Giscus.html
     repo = ""
     repoid = ""
     category = ""
     categoryid = ""
     mapping = ""
   [params.gitalk]
     clientID = "Your client ID" # Your client ID
     clientSecret = "Your client secret" # Your client secret
     repo = "your Repository name" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
     owner = "your GitHub ID" # æ‚¨çš„GitHub ID
   [params.Vssue]
	provider = ""  # set your OAuth peovider , now support "Github" "Gitlab" "Bitbucket" "Gitea" "Gitee"
	title = "" # set issue title
     clientID = "Your client ID" # Your client ID
     clientSecret = "Your client secret" # Your client secret
     repo = "Repository name" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
     owner = "GitHub ID" # æ‚¨çš„GitHud ID
	VueCDN = "jsdelivr" # "jsdelivr" or "unpkg" version:vue@2.7.14
     VueType = "full" # "full" or "runtime"
     template = false


  [[params.links]]
    title = "Link"
    href = "https://github.com/meik2333"

  [[params.links]]
    title = "Link2"
    href = "https://meik2333.com"
    icon = "https://meik2333.com/images/avatar.png"

  [[params.customOrgs]]
    link = "Custom link"
    img = "Custom img" 
    name = "Custom name"

  [params.Aplayer]
    Audio1 = ''
    Artist1 = ''
    Url1 = ''
    Cover1 = ''
    Audio2 = ''
    Artist2 = ''
    Url2 = ''
    Cover2 = ''
    Audio3 = ''
    Artist3 = ''
    Url3 = ''
    Cover3 = ''
    Audio4 = ''
    Artist4 = ''
    Url4 = ''
    Cover4 = ''

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
tag = "tags"
category = "categories"


