baseURL = "https://meik2333.com/"
languageCode = "zh-cn"
title = "MeiK's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  contributions = "post"
  author = "MeiK"
  github = "MeiK2333"
  description = "In solitude, where we are least alone."
  twitter = "MeiK2333"
  email = "meik2333@gmail.com"
  utterances = "MeiK2333/MeiK2333.github.io"
  facebook = "MeiK2333"
  url = "https://meik2333.com"
  keywords = "blog, google analytics"
  rss = true
  location = "China"
  lastmod = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
